### ISSUE TITLE
backport changes to credstash

### ISSUE THREAD

**Issue by ediskandarov-cur** [3stack-software/credsmash#1]
Credstash is used by many people and other frameworks,
such as [ansible](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/lookup/credstash.py).
It would be nice to have one utility serving the same purpose than two.

Is it possible to push updated back to original credstash?

**Comment by nathan-muir** [comment]
Hi @toidi 

We like having our own fork, as we can customise it to suit.

If the credstash maintainers would like to backport/copy any of the changes we've made, they're free to do so.

[I have attempted to make a CLI that's mostly compatible with `credstash`](https://github.com/3stack-software/credsmash/commits/credstash), so there is some hope of merging in the future.

However, the python API is quite different, so things like the ansible plugin would need to be rewritten.

**Comment by ediskandarov-cur** [comment]
got it. thank you.
I'll backport cryptography related stuff.
