### ISSUE TITLE
credstash backward compatibility

### ISSUE THREAD

**Issue by ediskandarov-cur** [3stack-software/credsmash#2]
What is the level of credstash compatibility?

Is it possible to switch to credsmash from credstash (at least for cli)?

**Comment by nathan-muir** [comment]
It's possible to read & write secrets in a compatible way between `credstash` and `credsmash`, though you lose out on some of the new features.

> Please set, algorithm = aes-ctr-legacy in your credsmash.cfg if you need to support credstash clients.

The CLI isn't compatible however:
1. [History.md](https://github.com/3stack-software/credsmash/blob/master/HISTORY.md) documents the changes between `credsmash` & `credstash`

2. The [`credstash` branch](https://github.com/3stack-software/credsmash/tree/credstash) has work on a compatible CLI , which I've started tracking in a new PR: https://github.com/3stack-software/credsmash/pull/4
